# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20241017-111621-dry-gain

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "LanguageModelFeaturizer"
  model: "bert-base-uncased"
- name: "DIETClassifier"
  epochs: 100
  random_seed: 42
  model_confidence: "softmax"
- name: "CRFEntityExtractor"  # Optional: if you want to use CRF for entity extraction
- name: "ResponseSelector"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- name: "RegexFeaturizer"
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
# - name: "SpacyNLP"
#   model: "en_core_web_md"    # or use "en_core_web_sm" if you have memory 
# - name: "WhitespaceTokenizer"
# - name: "LanguageModelFeaturizer"
#   model: "bert-base-uncased"
# - name: "SpacyTokenizer"
# - name: "SpacyFeaturizer"
# - name: "RegexFeaturizer"
# - name: "CRFEntityExtractor"
# - name: "ResponseSelector" 
# - name: "EntitySynonymMapper"
# - name: "CountVectorsFeaturizer"
# - name: "ResponseSelector"
# - name: "DIETClassifier"
#   epochs: 100
#   random_seed: 42
#   model_confidence: "linear"
# - name: "FallbackClassifier"
#   threshold: 0.3
# - name: WhitespaceTokenizer
# - name: RegexFeaturizer
# - name: LexicalSyntacticFeaturizer
# - name: CountVectorsFeaturizer
# - name: CountVectorsFeaturizer
#   analyzer: char_wb
#   min_ngram: 1
#   max_ngram: 4
# - name: DIETClassifier
#   epochs: 100
#   random_seed: 42
# - name: EntitySynonymMapper
# - name: ResponseSelector
#   epochs: 100
#   random_seed: 42
# - name: FallbackClassifier
#   threshold: 0.3
#   ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
- name: "MemoizationPolicy"
- name: "TEDPolicy"
  max_history: 5
  epochs: 100
- name: "RulePolicy"
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True
  
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
# - name: RulePolicy
# - name: MemoizationPolicy
# - name: TEDPolicy
#   max_history: 5
#   epochs: 100
# - name: FallbackPolicy
#   nlu_threshold: 0.3
#   core_threshold: 0.3
#   fallback_action_name: "action_default_fallback"
custom:
- name: "CustomPolicy"
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true